#!/usr/bin/env python3
"""Generate map_v1_external_source_catalog.csv with proper CSV quoting."""
import csv
from pathlib import Path

ROOT = Path(__file__).parent.parent

COLUMNS = [
    "source_id","provider","primary_or_reference","dataset_or_api_name","official_url",
    "data_class","spatial_coverage","spatial_resolution_or_station_rule","time_resolution",
    "timezone","update_frequency","authentication_required","license_or_terms",
    "license_evidence_url","allowed_map_use","allowed_cache_policy","required_attribution",
    "known_limitations","decision",
]

def R(**kw):
    return kw

ROWS = [
R(source_id="src-goocean-portal",provider="國家海洋研究院 (NAMR)",primary_or_reference="reference",dataset_or_api_name="GoOcean 海洋遊憩風險資訊平台",official_url="https://goocean.namr.gov.tw/",data_class="site_registry",spatial_coverage="全臺沿岸及離島",spatial_resolution_or_station_rule="地圖圖台（非原始資料產品）",time_resolution="不適用（展示圖台）",timezone="Asia/Taipei (UTC+8)",update_frequency="不適用",authentication_required="false",license_or_terms="服務條款（非商業有限再利用；第三方權利另行保留）",license_evidence_url="https://goocean.namr.gov.tw/ServiceTerms",allowed_map_use="reference_only",allowed_cache_policy="no_cache",required_attribution="標示「國家海洋研究院 GoOcean 平台」並保留來源連結；第三方素材不得轉發",known_limitations="圖台整合多個第三方機關資料；私有未公開 API 端點不穩定；風險燈號計算黑箱；不可依賴私有端點或複製未授權圖示",decision="reference_only"),
R(source_id="src-goocean-dive-layer",provider="國家海洋研究院 (NAMR)",primary_or_reference="reference",dataset_or_api_name="GoOcean 潛點圖層（介面參考）",official_url="https://goocean.namr.gov.tw/",data_class="site_registry",spatial_coverage="全臺沿岸及離島",spatial_resolution_or_station_rule="未公開（無圖層字典或要素版本）",time_resolution="不適用",timezone="Asia/Taipei (UTC+8)",update_frequency="不適用",authentication_required="false",license_or_terms="服務條款（第三方權利混雜；潛點資料來源未公開）",license_evidence_url="https://goocean.namr.gov.tw/ServiceTerms",allowed_map_use="reference_only",allowed_cache_policy="no_cache",required_attribution="不得再發布；僅人工線索查核",known_limitations="潛點圖層無公開資料字典、來源機關、座標精度或正式匯出方式；不得爬取或呼叫私有端點",decision="reference_only"),
R(source_id="src-cwa-obs-buoy",provider="交通部中央氣象署 (CWA)",primary_or_reference="primary",dataset_or_api_name="CWA 海象即時觀測資料浮標 O-B0076-001",official_url="https://opendata.cwa.gov.tw/dataset/all/O-B0076-001",data_class="live_observation",spatial_coverage="臺灣周邊海域（~20 站含澎湖/綠島/蘭嶼/東沙浮標）",spatial_resolution_or_station_rule="點位站觀測（Nearest-station Haversine；需標示距離與站名）",time_resolution="每小時",timezone="Asia/Taipei (UTC+8)",update_frequency="每小時",authentication_required="true",license_or_terms="政府資料開放授權條款第 1 版 (OGL 1.0)",license_evidence_url="https://data.gov.tw/dataset/all/O-B0076-001",allowed_map_use="live_overlay",allowed_cache_policy="ttl_1h",required_attribution="標示「交通部中央氣象署、資料集名稱及 OGL 1.0」",known_limitations="浮標站為點位觀測非現地量測；需顯示測站名稱+直線距離+觀測時間+地形遮蔽不確定性警語；不得表述為潛點現地海況",decision="approved_candidate"),
R(source_id="src-cwa-obs-tide",provider="交通部中央氣象署 (CWA)",primary_or_reference="primary",dataset_or_api_name="CWA 即時潮位觀測 O-B0070-001",official_url="https://opendata.cwa.gov.tw/dataset/observation/O-B0070-001",data_class="live_observation",spatial_coverage="臺灣周邊沿岸潮位站（~45 站含七美/吉貝/小琉球/蘭嶼/後壁湖/成功等）",spatial_resolution_or_station_rule="點位站觀測（Nearest-station Haversine；需標示距離與站名）",time_resolution="每小時",timezone="Asia/Taipei (UTC+8)",update_frequency="每小時",authentication_required="true",license_or_terms="政府資料開放授權條款第 1 版 (OGL 1.0)",license_evidence_url="https://data.gov.tw/dataset/observation/O-B0070-001",allowed_map_use="live_overlay",allowed_cache_policy="ttl_1h",required_attribution="標示「交通部中央氣象署、資料集名稱及 OGL 1.0」",known_limitations="潮位站為沿岸點位；離潛點可能有公里級距離差；不得作為安全判定",decision="approved_candidate"),
R(source_id="src-cwa-obs-wave",provider="交通部中央氣象署 (CWA)",primary_or_reference="primary",dataset_or_api_name="CWA 沿岸波浪觀測 O-B0075-001",official_url="https://opendata.cwa.gov.tw/dataset/observation/O-B0075-001",data_class="live_observation",spatial_coverage="臺灣沿岸固定波浪站（浮球式波浪站）",spatial_resolution_or_station_rule="點位站觀測（Nearest-station Haversine）",time_resolution="每小時",timezone="Asia/Taipei (UTC+8)",update_frequency="每小時",authentication_required="true",license_or_terms="政府資料開放授權條款第 1 版 (OGL 1.0)",license_evidence_url="https://data.gov.tw/dataset/observation/O-B0075-001",allowed_map_use="live_overlay",allowed_cache_policy="ttl_1h",required_attribution="標示「交通部中央氣象署、資料集名稱及 OGL 1.0」",known_limitations="波浪站數量少（< 10 站）；離島潛點覆蓋不足；不得表述為現地觀測",decision="approved_candidate"),
R(source_id="src-cwa-forecast-marine",provider="交通部中央氣象署 (CWA)",primary_or_reference="primary",dataset_or_api_name="CWA 休閒海域波流模式預報 M-B0078-001",official_url="https://opendata.cwa.gov.tw/dataset/observation/M-B0078-001",data_class="forecast",spatial_coverage="臺灣周邊海域（含離島海域格點）",spatial_resolution_or_station_rule="數值格點（格點間距未公開；已知測試點距最近格點 1.8–2.7 km）",time_resolution="每 6 小時",timezone="Asia/Taipei (UTC+8)",update_frequency="每 6 小時",authentication_required="true",license_or_terms="政府資料開放授權條款第 1 版 (OGL 1.0)",license_evidence_url="https://data.gov.tw/dataset/126373",allowed_map_use="forecast_drawer",allowed_cache_policy="ttl_6h",required_attribution="標示「交通部中央氣象署、M-B0078-001、OGL 1.0」",known_limitations="格點模式非現地量測；最近格點距潛點可能 > 1.8 km；需標示格點距離與預報不確定性；不得表述為潛點現地海況",decision="approved_candidate"),
R(source_id="src-cwa-forecast-coastal",provider="交通部中央氣象署 (CWA)",primary_or_reference="primary",dataset_or_api_name="CWA 沿海鄉鎮預報 F-D0047-095（含離島代表區）",official_url="https://opendata.cwa.gov.tw/dataset/forecast/F-D0047-095",data_class="forecast",spatial_coverage="臺灣本島與離島沿海 120 個代表區",spatial_resolution_or_station_rule="行政區/沿海代表區（需確認綠島/澎湖對應代碼）",time_resolution="每 3 小時（至 72 小時）",timezone="Asia/Taipei (UTC+8)",update_frequency="每 6 小時",authentication_required="true",license_or_terms="待確認（公開 API 頁面未明示 OGL）",license_evidence_url="https://opendata.cwa.gov.tw/dataset/forecast/F-D0047-095",allowed_map_use="forecast_drawer",allowed_cache_policy="no_cache",required_attribution="待授權確認後標示",known_limitations="需確認正式位置清單與公開再利用條款；現階段暫緩",decision="pending_rights_review"),
R(source_id="src-cwa-forecast-county",provider="交通部中央氣象署 (CWA)",primary_or_reference="primary",dataset_or_api_name="CWA 鄉鎮一般天氣預報 F-D0047-037/045（臺東/澎湖縣）",official_url="https://data.gov.tw/dataset/9281",data_class="forecast",spatial_coverage="臺東縣（含綠島鄉）及澎湖縣（含白沙鄉等）",spatial_resolution_or_station_rule="行政區鄉鎮對應（LocationName 完全匹配）",time_resolution="每 3 小時（至 3 天）",timezone="Asia/Taipei (UTC+8)",update_frequency="每 6 小時",authentication_required="true",license_or_terms="政府資料開放授權條款第 1 版 (OGL 1.0)",license_evidence_url="https://data.gov.tw/dataset/9281",allowed_map_use="forecast_drawer",allowed_cache_policy="ttl_6h",required_attribution="標示「交通部中央氣象署、資料集名稱及 OGL 1.0、IssueTime、有效時間」",known_limitations="一般天氣預報（氣溫/降水/風速）非海況；顯示名稱必須為「XX 鄉一般天氣預報」不可稱潛點海況；資料年齡超過 8 小時應顯示過舊警告",decision="approved_candidate"),
R(source_id="src-cwa-forecast-ocean",provider="交通部中央氣象署 (CWA)",primary_or_reference="primary",dataset_or_api_name="CWA 海域天氣預報 F-A0012-001",official_url="https://opendata.cwa.gov.tw/dataset/forecast/F-A0012-001",data_class="forecast",spatial_coverage="具名海域（臺灣東部/西部/北部/南部/巴士海峽等）",spatial_resolution_or_station_rule="海域區域（無具體邊界座標）",time_resolution="每 12 小時（至 48 小時）",timezone="Asia/Taipei (UTC+8)",update_frequency="每 6 小時",authentication_required="true",license_or_terms="待確認",license_evidence_url="https://opendata.cwa.gov.tw/dataset/forecast/F-A0012-001",allowed_map_use="forecast_drawer",allowed_cache_policy="no_cache",required_attribution="待授權確認後標示",known_limitations="需確認正式海域邊界座標與公開再利用條款；現階段暫緩",decision="pending_rights_review"),
R(source_id="src-namr-nodass",provider="國家海洋研究院 (NAMR)",primary_or_reference="primary",dataset_or_api_name="NAMR NODASS 國家海洋資料庫（開放測站資料）",official_url="https://www.namr.gov.tw/",data_class="live_observation",spatial_coverage="臺灣周邊海域（含墾丁南灣、花蓮等 NAMR 浮標站）",spatial_resolution_or_station_rule="點位站觀測（需確認測站名冊與座標）",time_resolution="不定（依測站類型）",timezone="Asia/Taipei (UTC+8)",update_frequency="不定",authentication_required="true",license_or_terms="待確認（NAMR 開放資料條款）",license_evidence_url="https://www.namr.gov.tw/",allowed_map_use="live_overlay",allowed_cache_policy="no_cache",required_attribution="待授權確認後標示",known_limitations="NAMR NODASS 正式開放 API 端點與授權條款需向 NAMR 查詢確認；現階段暫緩",decision="pending_rights_review"),
R(source_id="src-tourism-attraction",provider="交通部觀光署",primary_or_reference="primary",dataset_or_api_name="景點－觀光資訊資料庫（含浮潛/潛水景點）",official_url="https://data.gov.tw/dataset/7777",data_class="site_registry",spatial_coverage="全臺（含離島）",spatial_resolution_or_station_rule="點位（WGS84；需逐筆確認為潛水/浮潛地點）",time_resolution="每日更新（靜態）",timezone="Asia/Taipei (UTC+8)",update_frequency="每日",authentication_required="false",license_or_terms="政府資料開放授權條款第 1 版 (OGL 1.0)",license_evidence_url="https://data.gov.tw/dataset/7777",allowed_map_use="vector_marker",allowed_cache_policy="ttl_24h",required_attribution="標示「交通部觀光署、景點－觀光資訊資料庫（觀光資料標準 V2.1）」",known_limitations="僅明確記載為潛水/浮潛地點者可列入；一般景點/釣點/調查站不得自動升格為潛點；媒體另有著作權",decision="approved_candidate"),
R(source_id="src-ocean-recreation-platform",provider="行政院農業委員會漁業署/海洋委員會",primary_or_reference="primary",dataset_or_api_name="海域遊憩活動一站式服務平台",official_url="https://ocean.gov.tw/",data_class="site_registry",spatial_coverage="全臺沿岸海域",spatial_resolution_or_station_rule="行政區或海域區域（非精確座標）",time_resolution="不定（靜態資訊為主）",timezone="Asia/Taipei (UTC+8)",update_frequency="不定",authentication_required="false",license_or_terms="政府網站（待確認再發布條款）",license_evidence_url="https://ocean.gov.tw/",allowed_map_use="reference_only",allowed_cache_policy="no_cache",required_attribution="標示主管機關與資料來源",known_limitations="服務範圍/規定文字為管理背景資訊；不等於潛點名冊；需逐條確認再發布授權",decision="pending_rights_review"),
R(source_id="src-taibif-occurrence",provider="農業部生物多樣性研究所/TaiBIF",primary_or_reference="primary",dataset_or_api_name="TaiBIF 全球生物多樣性資料庫（臺灣生物調查資料）",official_url="https://www.taibif.tw/",data_class="species_occurrence",spatial_coverage="全臺（含海域）；本機已有 414 MB JSON",spatial_resolution_or_station_rule="點位（decimalLatitude/decimalLongitude；精度依調查方法）",time_resolution="歷史調查（靜態）",timezone="UTC（eventDate 欄位）",update_frequency="歷史一次性（版本更新）",authentication_required="false",license_or_terms="CC BY 4.0（預設；各資料集需個別確認）",license_evidence_url="https://www.taibif.tw/zh/page/termsofuse",allowed_map_use="species_list",allowed_cache_policy="immutable_local",required_attribution="標示「TaiBIF、資料集來源機關、採樣日期及方法」",known_limitations="歷史物種出現紀錄不等於目前現地可見；坐標精度依調查計畫；不輸出精確敏感物種位置（瀕危物種座標需模糊化）",decision="approved_candidate"),
R(source_id="src-taicol-taxonomy",provider="農業部生物多樣性研究所/TaiCOL",primary_or_reference="primary",dataset_or_api_name="TaiCOL 臺灣物種名錄",official_url="https://taicol.tw/",data_class="species_occurrence",spatial_coverage="全臺（分類名錄）",spatial_resolution_or_station_rule="無空間座標（分類學）",time_resolution="歷史靜態（版本化）",timezone="不適用",update_frequency="每季更新",authentication_required="false",license_or_terms="CC BY 4.0",license_evidence_url="https://taicol.tw/about",allowed_map_use="species_list",allowed_cache_policy="immutable_local",required_attribution="標示「TaiCOL 臺灣物種名錄及版本日期」",known_limitations="分類名錄不含出現紀錄座標；僅可作為物種鑑定與中英文名稱標準化依據",decision="approved_candidate"),
R(source_id="src-local-cwa-hydro",provider="交通部中央氣象署 (CWA)",primary_or_reference="primary",dataset_or_api_name="本機 CWA 歷史海氣象水文觀測（qc＋realtime CSV）",official_url="https://opendata.cwa.gov.tw/",data_class="historical_ecology",spatial_coverage="臺灣周邊沿岸（~45 站含七美/吉貝/小琉球/蘭嶼/後壁湖/成功/龍洞等）",spatial_resolution_or_station_rule="點位站（LonLat.csv WGS84 座標）",time_resolution="年度 CSV（2023/2024/2025）每列一筆觀測",timezone="Asia/Taipei (UTC+8)（推定）",update_frequency="歷史靜態（已下載）",authentication_required="false",license_or_terms="政府資料開放授權條款第 1 版 (OGL 1.0)（推定）",license_evidence_url="https://opendata.cwa.gov.tw/",allowed_map_use="live_overlay",allowed_cache_policy="immutable_local",required_attribution="標示「交通部中央氣象署、資料集 ID、OGL 1.0」",known_limitations="本機歷史資料不是即時資料；qc（品管）版與 realtime（即時）版資料品質不同；欄位含 StationID/time/Wind_Speed/Sea_Temperature/Wave_Height_Significant/Tide_Height/CenterLongitude/CenterLatitude",decision="approved_candidate"),
R(source_id="src-local-ihmt-hydro",provider="港灣技術研究中心 (IHMT)",primary_or_reference="primary",dataset_or_api_name="本機 IHMT 港研所歷史海氣象觀測 CSV",official_url="https://www.ihmt.gov.tw/",data_class="historical_ecology",spatial_coverage="臺灣主要港灣（馬公港/基隆港等；LonLat.csv 有座標）",spatial_resolution_or_station_rule="點位站（qc 子目錄；LonLat.csv WGS84 座標）",time_resolution="年度 CSV（qc 版）",timezone="Asia/Taipei (UTC+8)（推定）",update_frequency="歷史靜態（已下載）",authentication_required="false",license_or_terms="待確認（IHMT 資料授權條款）",license_evidence_url="https://www.ihmt.gov.tw/",allowed_map_use="environmental_data_candidate",allowed_cache_policy="no_cache",required_attribution="待確認後標示主管機關",known_limitations="港灣觀測距外海潛點可能有公里級距離差；港灣地形效應影響代表性；授權待確認",decision="pending_rights_review"),
R(source_id="src-local-namr-hydro",provider="國家海洋研究院 (NAMR)",primary_or_reference="primary",dataset_or_api_name="本機 NAMR 浮標站歷史觀測 CSV",official_url="https://www.namr.gov.tw/",data_class="historical_ecology",spatial_coverage="臺灣外海及離島（含墾丁南灣/花蓮等 NAMR 站；LonLat.csv 有座標）",spatial_resolution_or_station_rule="點位站（qc＋realtime 子目錄；LonLat.csv WGS84 座標）",time_resolution="年度 CSV（2023/2024/2025）",timezone="Asia/Taipei (UTC+8)（推定）",update_frequency="歷史靜態（已下載）",authentication_required="false",license_or_terms="待確認（NAMR 開放資料條款）",license_evidence_url="https://www.namr.gov.tw/",allowed_map_use="environmental_data_candidate",allowed_cache_policy="no_cache",required_attribution="待確認後標示主管機關",known_limitations="NAMR 正式授權條款需確認；浮標觀測代表性受地形影響",decision="pending_rights_review"),
R(source_id="src-local-wra-hydro",provider="水利署 (WRA)",primary_or_reference="primary",dataset_or_api_name="本機 WRA 水利署潮位資料 CSV",official_url="https://www.wra.gov.tw/",data_class="historical_ecology",spatial_coverage="臺灣沿岸（WRA 潮位站；LonLat.csv 有座標）",spatial_resolution_or_station_rule="點位站（LonLat.csv WGS84 座標）",time_resolution="年度 CSV",timezone="Asia/Taipei (UTC+8)（推定）",update_frequency="歷史靜態（已下載）",authentication_required="false",license_or_terms="待確認（WRA 資料授權條款）",license_evidence_url="https://www.wra.gov.tw/",allowed_map_use="environmental_data_candidate",allowed_cache_policy="no_cache",required_attribution="待確認後標示主管機關",known_limitations="WRA 授權條款需確認；主要為河口潮位站",decision="pending_rights_review"),
R(source_id="src-local-oca-wq",provider="海洋委員會海洋保育署 (OCA)",primary_or_reference="primary",dataset_or_api_name="本機 OCA 海保署海域水質監測資料 CSV",official_url="https://data.gov.tw/",data_class="historical_ecology",spatial_coverage="臺灣沿岸（OCA 水質監測站；LonLat.csv 有座標）",spatial_resolution_or_station_rule="點位站（LonLat.csv WGS84 座標）",time_resolution="2023-2025 CSV；欄位含 Air_Temperature/Salinity/Water_Temperature/pH_Value/Dissolved_Oxygen/Chlorophyll_a 等",timezone="Asia/Taipei (UTC+8)（推定）",update_frequency="歷史靜態（已下載）",authentication_required="false",license_or_terms="政府資料開放授權條款第 1 版 (OGL 1.0)（推定）",license_evidence_url="https://data.gov.tw/",allowed_map_use="environmental_data_candidate",allowed_cache_policy="immutable_local",required_attribution="待確認後標示「海洋委員會海洋保育署、OGL 1.0」",known_limitations="水質資料非即時海況；需確認實際採集時間與授權版本",decision="pending_rights_review"),
R(source_id="src-local-edna",provider="海洋委員會海洋保育署 (OCA)",primary_or_reference="primary",dataset_or_api_name="本機 eDNA 全海域基礎生態調查（12S/16S/18S）JSON",official_url="https://data.gov.tw/en/datasets/172487",data_class="historical_ecology",spatial_coverage="臺灣周邊海域（多個採樣站點；Longitude/Latitude 欄位）",spatial_resolution_or_station_rule="點位站（StationId/Longitude/Latitude；6 個 JSON 涵蓋 109-112 年四季）",time_resolution="歷史調查（季別）109-112 年",timezone="不適用（非時間序列）",update_frequency="歷史一次性",authentication_required="false",license_or_terms="政府資料開放授權條款第 1 版 (OGL 1.0)（推定）",license_evidence_url="https://data.gov.tw/en/datasets/172487",allowed_map_use="species_list",allowed_cache_policy="immutable_local",required_attribution="標示「海洋委員會海洋保育署、OGL 1.0」",known_limitations="eDNA 歷史採樣不等於目前現地可見物種；基因標記（12S/16S/18S）對應物種有解析度限制；採樣年份涵蓋 2020-2023",decision="approved_candidate"),
R(source_id="src-local-eco-survey",provider="國立海洋生物博物館 (NMMBA)",primary_or_reference="primary",dataset_or_api_name="本機全海域基礎生態調查（海生中心示範海域）XLSX",official_url="https://www.namr.gov.tw/",data_class="historical_ecology",spatial_coverage="北部/南部/澎湖海域（三個分區 Excel 共 1.19 MB）",spatial_resolution_or_station_rule="調查站點（Excel 欄位含分類群與站位資訊；CRS 未確認）",time_resolution="歷史調查（110 年 11 月）",timezone="不適用（靜態）",update_frequency="歷史一次性",authentication_required="false",license_or_terms="待確認（NMMBA/全國海洋資料庫授權）",license_evidence_url="https://www.namr.gov.tw/",allowed_map_use="historical_ecology",allowed_cache_policy="no_cache",required_attribution="待確認後標示主管機關",known_limitations="需確認 Excel 欄位結構、分類群與座標欄名稱；授權需向 NMMBA/NAMR 確認；xlsx 未安裝解析套件時記錄未能驗證",decision="pending_rights_review"),
R(source_id="src-local-beach-gis",provider="海洋委員會海洋保育署 (OCA)/環境部",primary_or_reference="primary",dataset_or_api_name="本機全國海灘環境調查 Shapefile/GeoJSON/KML（39 個檔案）",official_url="https://www.oca.gov.tw/",data_class="historical_ecology",spatial_coverage="全臺海岸（突堤/防護工/釣點/安檢所/高潮線/植生/沙灘/看板/礁岩圖層）",spatial_resolution_or_station_rule="多邊形/線段/點位（EPSG:4326 WGS84 已確認）",time_resolution="歷史靜態（調查年份未知）",timezone="不適用",update_frequency="歷史一次性",authentication_required="false",license_or_terms="待確認（海調資料來源授權）",license_evidence_url="https://www.oca.gov.tw/",allowed_map_use="vector_marker",allowed_cache_policy="no_cache",required_attribution="待確認後標示主管機關",known_limitations="礁岩/沙灘/高潮線為環境幾何；不可自動升格為潛點；安檢所/海巡隊位置屬行政點位非潛點；授權待確認",decision="pending_rights_review"),
R(source_id="src-local-reef-locations",provider="UNEP-WCMC（推定；授權待確認）",primary_or_reference="reference",dataset_or_api_name="92_全球珊瑚礁位置 CSV+Shapefile（ReefLocations.csv）",official_url="https://www.unep-wcmc.org/",data_class="historical_ecology",spatial_coverage="全球（需篩選臺灣範圍）；EPSG:4326 已確認",spatial_resolution_or_station_rule="點位（ID/REGION/COUNTRY/LOCATION/LAT/LON/REEF_SYSTEM/REEF_TYPE/REEF_NAME 欄位）",time_resolution="歷史靜態（來源年份未知）",timezone="不適用",update_frequency="歷史一次性",authentication_required="false",license_or_terms="待確認（UNEP-WCMC 授權條款）",license_evidence_url="https://www.unep-wcmc.org/",allowed_map_use="reference_only",allowed_cache_policy="no_cache",required_attribution="待確認後標示主管機關",known_limitations="全球資料不可因與海洋相關就列為臺灣浮潛知識；授權未確認；需篩選臺灣範圍後再評估；礁位點不等於休閒潛點",decision="pending_rights_review"),
R(source_id="src-local-dscrtp",provider="NOAA DSCRTP",primary_or_reference="reference",dataset_or_api_name="全球深海珊瑚與海綿位置 DSCRTP CSV（2.56 GB）",official_url="https://deepseacoraldata.noaa.gov/",data_class="historical_ecology",spatial_coverage="全球深海（超出休閒潛水範圍；主要 > 30 m）",spatial_resolution_or_station_rule="點位（ShallowFlag/decimalLatitude/decimalLongitude）",time_resolution="歷史靜態（版本 20260416）",timezone="UTC",update_frequency="歷史一次性",authentication_required="false",license_or_terms="待確認（NOAA 資料授權）",license_evidence_url="https://deepseacoraldata.noaa.gov/",allowed_map_use="reference_only",allowed_cache_policy="no_cache",required_attribution="標示「NOAA DSCRTP」",known_limitations="深海（> 30 m）超出休閒潛水範圍；2.56 GB 大型資料；全球範圍不可直接用於臺灣潛點；授權待確認",decision="excluded"),
R(source_id="src-local-fishing-kml",provider="海洋委員會/漁業署",primary_or_reference="primary",dataset_or_api_name="本機全台開放釣點位置 KML（38 KB）",official_url="https://www.oca.gov.tw/",data_class="site_registry",spatial_coverage="全臺沿岸（KML 點位）",spatial_resolution_or_station_rule="點位（WGS84 KML；欄位待確認）",time_resolution="歷史靜態（調查年份未知）",timezone="不適用",update_frequency="歷史一次性",authentication_required="false",license_or_terms="待確認",license_evidence_url="https://www.oca.gov.tw/",allowed_map_use="reference_only",allowed_cache_policy="no_cache",required_attribution="待確認後標示主管機關",known_limitations="釣點不等於潛點；不可自動升格為潛點；需人工逐筆確認",decision="pending_rights_review"),
R(source_id="src-local-strand",provider="海洋委員會海洋保育署 (OCA)",primary_or_reference="primary",dataset_or_api_name="本機海洋生物擱淺紀錄 JSON（海龜 944 筆 + 鯨豚 430 筆）",official_url="https://www.oca.gov.tw/",data_class="historical_ecology",spatial_coverage="全臺沿岸（CenterLatitude/CenterLongitude；EarliestDate/LatestDate）",spatial_resolution_or_station_rule="點位（含 BoundingBox；Title/GeoProductID 欄位）",time_resolution="歷史靜態（各事件日期）",timezone="不適用",update_frequency="歷史一次性",authentication_required="false",license_or_terms="待確認（OCA 授權）",license_evidence_url="https://www.oca.gov.tw/",allowed_map_use="reference_only",allowed_cache_policy="no_cache",required_attribution="待確認後標示主管機關",known_limitations="敏感物種（海龜/鯨豚）擱淺位置不得精確輸出（須模糊化到縣市級別）；擱淺事件非潛點資訊；授權待確認",decision="pending_rights_review"),
R(source_id="src-local-eco-monitoring",provider="海洋委員會海洋保育署 (OCA)",primary_or_reference="primary",dataset_or_api_name="本機海域生態監測站點 JSON + JPG/MP4 影像（87 個檔案）",official_url="https://www.oca.gov.tw/",data_class="image_link_only",spatial_coverage="全臺（含恆春/花蓮/臺東/澎湖等監測站；CenterLatitude/CenterLongitude 欄位）",spatial_resolution_or_station_rule="點位（54 筆 JSON；JPG/MP4 影像）",time_resolution="歷史靜態（調查年份未知）",timezone="不適用",update_frequency="歷史一次性",authentication_required="false",license_or_terms="待確認（OCA 著作權）",license_evidence_url="https://www.oca.gov.tw/",allowed_map_use="image_link_only",allowed_cache_policy="no_cache",required_attribution="待確認後標示主管機關",known_limitations="JPG/MP4 影像著作權未確認；嚴禁自動抓取或內嵌；JSON 點位可用但監測站不等於潛點",decision="image_link_only"),
R(source_id="src-local-fish-db",provider="中央研究院生物多樣性研究中心",primary_or_reference="primary",dataset_or_api_name="本機臺灣魚類資料庫 CSV（1.12 MB）",official_url="https://fishdb.sinica.edu.tw/",data_class="species_occurrence",spatial_coverage="臺灣（分類與分布）",spatial_resolution_or_station_rule="無座標（分類學）",time_resolution="歷史靜態（2020 年後修改）",timezone="不適用",update_frequency="歷史一次性",authentication_required="false",license_or_terms="待確認（中研院 TaiCoL/TaiBIF 條款）",license_evidence_url="https://fishdb.sinica.edu.tw/",allowed_map_use="species_list",allowed_cache_policy="immutable_local",required_attribution="標示「中央研究院生物多樣性研究中心臺灣魚類資料庫」",known_limitations="魚類分類名錄不含出現座標；僅作物種名稱標準化依據；不表述為現地可見",decision="approved_candidate"),
R(source_id="src-local-trawl",provider="中央研究院生物多樣性研究中心",primary_or_reference="primary",dataset_or_api_name="本機臺灣底拖與深海採集資料 DwC-A CSV（底拖 2.24 MB + 深海 1.64 MB）",official_url="https://www.taibif.tw/",data_class="historical_ecology",spatial_coverage="臺灣周邊海域（decimalLatitude/decimalLongitude；深度欄位）",spatial_resolution_or_station_rule="點位（DwC-A 欄位：occurrenceID/eventDate/decimalLatitude/decimalLongitude/minimumDepthInMeters/maximumDepthInMeters/samplingProtocol）",time_resolution="歷史調查（eventDate 欄位；底拖至 2012；深海至 2014 年前後）",timezone="UTC（eventDate 格式含時間）",update_frequency="歷史一次性",authentication_required="false",license_or_terms="待確認（中研院/TaiBIF CC BY？）",license_evidence_url="https://www.taibif.tw/",allowed_map_use="historical_ecology",allowed_cache_policy="immutable_local",required_attribution="標示「中央研究院生物多樣性研究中心、TaiBIF、採樣方法與日期」",known_limitations="底拖採集主要為研究非休閒潛水；深海子集超出休閒範圍；不表述為目前現地可見物種；授權待確認",decision="approved_candidate"),
R(source_id="src-local-research-doc",provider="使用者提供（高雄科技大學）",primary_or_reference="reference",dataset_or_api_name="珊瑚礁浮潛決策支援專題資料盤點與研究規劃 DOCX",official_url="https://www.nkust.edu.tw/",data_class="historical_ecology",spatial_coverage="不適用",spatial_resolution_or_station_rule="不適用",time_resolution="不適用",timezone="不適用",update_frequency="歷史一次性",authentication_required="false",license_or_terms="使用者提供（不可再發布）",license_evidence_url="https://www.nkust.edu.tw/",allowed_map_use="reference_only",allowed_cache_policy="no_cache",required_attribution="不適用",known_limitations="內部研究規劃文件；不可作為對使用者問答的事實來源；不含可公開引用的原始資料",decision="excluded"),
R(source_id="src-local-tmp-work",provider="使用者提供（暫存）",primary_or_reference="reference",dataset_or_api_name="tmp_work 暫存工作資料夾（Python 腳本 + PNG 報告圖）",official_url="https://www.nkust.edu.tw/",data_class="historical_ecology",spatial_coverage="不適用",spatial_resolution_or_station_rule="不適用",time_resolution="不適用",timezone="不適用",update_frequency="不適用",authentication_required="false",license_or_terms="不適用",license_evidence_url="https://www.nkust.edu.tw/",allowed_map_use="reference_only",allowed_cache_policy="no_cache",required_attribution="不適用",known_limitations="暫存腳本與報告素材；不得作為任何資料來源",decision="excluded"),
]

out_path = ROOT / "metadata" / "map_v1_external_source_catalog.csv"
with open(out_path, "w", encoding="utf-8-sig", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=COLUMNS)
    writer.writeheader()
    for row in ROWS:
        writer.writerow({col: row.get(col, "") for col in COLUMNS})

print(f"Written {len(ROWS)} rows to {out_path}")
