#!/usr/bin/env python3
"""generate_biodiversity_candidates.py

Generates metadata/map_v1_site_biodiversity_evidence_candidates.csv
and metadata/map_v1_site_biodiversity_evidence_report.md
for Map Task 14.
"""

import csv
import math
import os
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "data" / "runtime" / "research" / "marine_research.sqlite"
CURATED_CSV = ROOT / "data" / "curated" / "dive_sites.csv"
OUTPUT_CSV = ROOT / "metadata" / "map_v1_site_biodiversity_evidence_candidates.csv"
OUTPUT_REPORT = ROOT / "metadata" / "map_v1_site_biodiversity_evidence_report.md"

def haversine(lat1, lon1, lat2, lon2):
    R = 6371000
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)
    a = math.sin(delta_phi / 2)**2 + math.cos(phi1) * math.cos(phi2) * math.sin(delta_lambda / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return round(R * c, 1)

def main():
    print(f"Opening DB: {DB_PATH}")
    con = sqlite3.connect(DB_PATH)
    cur = con.cursor()

    # Load 5 dive sites
    with open(CURATED_CSV, "r", encoding="utf-8") as f:
        sites = list(csv.DictReader(f))
    print(f"Loaded {len(sites)} dive sites.")

    candidates = [
        # ==========================================
        # Site 1: 石朗潛水區 (tourism-attraction-376540000a-000365)
        # ==========================================
        {
            "candidate_id": "CAND-SL-RC-01",
            "site_id": "tourism-attraction-376540000a-000365",
            "site_name": "石朗潛水區",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Chaetodontidae",
            "taxon_chinese_name": "蝶魚科",
            "taxon_group": "魚類",
            "survey_method": "Reef Check 水下穿越線目視計數 (Belt Transect)",
            "record_date": "2018-04-23",
            "original_station_or_locality": "石朗(Shihlang)",
            "original_latitude": 22.654828,
            "original_longitude": 121.473514,
            "distance_m": haversine(22.65577, 121.47454, 22.654828, 121.473514),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:event_2018_TTLudao_Shihlang_deep_50-70",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "測線距潛點 148.5m；具明確觀測時點與穿越線目視方法。受 CC BY-NC 4.0 限制僅供非商業研究模式，且屬歷史調查紀錄，不得描述為現場必然可見之生態現況。"
        },
        {
            "candidate_id": "CAND-SL-RC-02",
            "site_id": "tourism-attraction-376540000a-000365",
            "site_name": "石朗潛水區",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Scaridae",
            "taxon_chinese_name": "鸚哥魚科",
            "taxon_group": "魚類",
            "survey_method": "Reef Check 水下穿越線目視計數 (Belt Transect)",
            "record_date": "2018-04-23",
            "original_station_or_locality": "石朗(Shihlang)",
            "original_latitude": 22.654828,
            "original_longitude": 121.473514,
            "distance_m": haversine(22.65577, 121.47454, 22.654828, 121.473514),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:event_2018_TTLudao_Shihlang_deep_0-20",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "測線距潛點 148.5m；具明確目視指標計數紀錄。限非商業研究模式使用，不得表述為目前現況。"
        },
        {
            "candidate_id": "CAND-SL-RC-03",
            "site_id": "tourism-attraction-376540000a-000365",
            "site_name": "石朗潛水區",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Tridacna sp.",
            "taxon_chinese_name": "砗磲貝屬",
            "taxon_group": "無脊椎動物",
            "survey_method": "Reef Check 水下穿越線無脊椎目視計數",
            "record_date": "2018-04-23",
            "original_station_or_locality": "石朗(Shihlang)",
            "original_latitude": 22.654828,
            "original_longitude": 121.473514,
            "distance_m": haversine(22.65577, 121.47454, 22.654828, 121.473514),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:event_2018_TTLudao_Shihlang_deep_0-20",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "測線距潛點 148.5m；記錄到健康砗磲貝個體。限非商業研究模式，不得保證現地可見。"
        },
        {
            "candidate_id": "CAND-SL-RC-04",
            "site_id": "tourism-attraction-376540000a-000365",
            "site_name": "石朗潛水區",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Scleractinia (hard coral)",
            "taxon_chinese_name": "硬珊瑚/石珊瑚覆蓋度",
            "taxon_group": "珊瑚",
            "survey_method": "Reef Check 點截線底質覆蓋度調查 (Point Intercept Transect)",
            "record_date": "2018-04-23",
            "original_station_or_locality": "石朗(Shihlang)",
            "original_latitude": 22.654828,
            "original_longitude": 121.473514,
            "distance_m": haversine(22.65577, 121.47454, 22.654828, 121.473514),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:measurementorfact.txt",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "距潛點 148.5m 之底質覆蓋度量測；非單一物種目擊，為底質群落歷史指標。僅限非商業研究使用，不得表述為現況。"
        },
        {
            "candidate_id": "CAND-SL-EDNA-01",
            "site_id": "tourism-attraction-376540000a-000365",
            "site_name": "石朗潛水區",
            "evidence_type": "environmental_dna",
            "taxon_scientific_name": "Acanthurus lineatus",
            "taxon_chinese_name": "線紋刺尾鯛",
            "taxon_group": "魚類",
            "survey_method": "水樣抽濾與次世代定序 (12S eDNA metabarcoding)",
            "record_date": "2022-06-28",
            "original_station_or_locality": "TRM59",
            "original_latitude": 22.654467,
            "original_longitude": 121.472817,
            "distance_m": haversine(22.65577, 121.47454, 22.654467, 121.472817),
            "source_name": "海洋委員會海洋保育署 (OCA) 全海域基礎生態調查環境DNA",
            "source_dataset_id": "edna_diving_110_113.json:TRM59",
            "source_url": "https://data.gov.tw/dataset/172487",
            "license_name": "政府資料開放授權條款-第1版 (OGL 1.0)",
            "license_status": "open_government_license",
            "decision": "accepted_historical_dna_evidence",
            "justification": "採樣站距潛點 228.6m；為水體環境 DNA 檢出分子訊號。嚴禁表述為潛水時肉眼必然可見或保證存在該個體。"
        },
        {
            "candidate_id": "CAND-SL-EDNA-02",
            "site_id": "tourism-attraction-376540000a-000365",
            "site_name": "石朗潛水區",
            "evidence_type": "environmental_dna",
            "taxon_scientific_name": "Amphiprion clarkii",
            "taxon_chinese_name": "克氏雙鋸魚",
            "taxon_group": "魚類",
            "survey_method": "水樣抽濾與次世代定序 (12S eDNA metabarcoding)",
            "record_date": "2022-06-28",
            "original_station_or_locality": "TRM59",
            "original_latitude": 22.654467,
            "original_longitude": 121.472817,
            "distance_m": haversine(22.65577, 121.47454, 22.654467, 121.472817),
            "source_name": "海洋委員會海洋保育署 (OCA) 全海域基礎生態調查環境DNA",
            "source_dataset_id": "edna_diving_110_113.json:TRM59",
            "source_url": "https://data.gov.tw/dataset/172487",
            "license_name": "政府資料開放授權條款-第1版 (OGL 1.0)",
            "license_status": "open_government_license",
            "decision": "accepted_historical_dna_evidence",
            "justification": "距潛點 228.6m 水樣中偵測出小丑魚基因分子片段。僅證明歷史水樣訊號，不等同肉眼可見。"
        },
        {
            "candidate_id": "CAND-SL-TAX-01",
            "site_id": "tourism-attraction-376540000a-000365",
            "site_name": "石朗潛水區",
            "evidence_type": "taxonomic_catalog",
            "taxon_scientific_name": "Chaetodon speculum",
            "taxon_chinese_name": "鏡斑蝴蝶魚",
            "taxon_group": "魚類",
            "survey_method": "分類學名錄整編 (無空間座標/無調查日期)",
            "record_date": "",
            "original_station_or_locality": "全臺魚類分類名錄(無地名)",
            "original_latitude": None,
            "original_longitude": None,
            "distance_m": None,
            "source_name": "中央研究院生物多樣性研究中心 臺灣魚類資料庫",
            "source_dataset_id": "臺灣魚類資料庫.csv",
            "source_url": "https://fishdb.sinica.edu.tw/",
            "license_name": "TaiBIF / TaiCoL 授權條款待確認",
            "license_status": "pending_verification",
            "decision": "excluded_taxonomy_only",
            "justification": "分類名錄不具空間座標與現場調查日期，僅能作物種名稱標準化與中英文對照，不得作為該潛點現地出現紀錄。"
        },
        {
            "candidate_id": "CAND-SL-IMG-01",
            "site_id": "tourism-attraction-376540000a-000365",
            "site_name": "石朗潛水區",
            "evidence_type": "monitoring_site_media",
            "taxon_scientific_name": "Scleractinia spp.",
            "taxon_chinese_name": "珊瑚礁群落 (監測站影像)",
            "taxon_group": "珊瑚",
            "survey_method": "定點水下生態攝影 (海域生態監測站)",
            "record_date": "",
            "original_station_or_locality": "綠島北岸(珊瑚礁)",
            "original_latitude": 22.6772,
            "original_longitude": 121.4925,
            "distance_m": haversine(22.65577, 121.47454, 22.6772, 121.4925),
            "source_name": "國家海洋研究院 (NAMR) 海域生態監測站點圖資",
            "source_dataset_id": "海域生態監測站點/36_綠島北岸(珊瑚礁).jpg",
            "source_url": "https://nodass.namr.gov.tw/noapidata/Tile/eDNA/mecrcPoint/36_綠島北岸(珊瑚礁).jpg",
            "license_name": "著作權未確認 (版權保留)",
            "license_status": "copyright_unclear_or_reserved",
            "decision": "pending_rights_review",
            "justification": "距離潛點 3.01 km 且影像著作權未確認開放。嚴禁下載、複製、快取或內嵌至地圖中。"
        },

        # ==========================================
        # Site 2: 綠島南寮漁港 (tourism-attraction-376540000a-000367)
        # ==========================================
        {
            "candidate_id": "CAND-NL-RC-01",
            "site_id": "tourism-attraction-376540000a-000367",
            "site_name": "綠島南寮漁港",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Chaetodontidae",
            "taxon_chinese_name": "蝶魚科",
            "taxon_group": "魚類",
            "survey_method": "Reef Check 水下穿越線目視計數",
            "record_date": "2018-04-23",
            "original_station_or_locality": "石朗(Shihlang)",
            "original_latitude": 22.654828,
            "original_longitude": 121.473514,
            "distance_m": haversine(22.65791, 121.47449, 22.654828, 121.473514),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:event_2018_TTLudao_Shihlang_deep_50-70",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "excluded_unrelated_habitat",
            "justification": "測線位於石朗外礁（距漁港 357.1m）。南寮漁港為防波堤、碼頭與航道之人造港區，港池內部無珊瑚礁測線；嚴禁將鄰近外礁生態冒稱為漁港內部現況。"
        },
        {
            "candidate_id": "CAND-NL-RC-02",
            "site_id": "tourism-attraction-376540000a-000367",
            "site_name": "綠島南寮漁港",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Scleractinia (hard coral)",
            "taxon_chinese_name": "硬珊瑚/石珊瑚覆蓋度",
            "taxon_group": "珊瑚",
            "survey_method": "Reef Check 點截線底質覆蓋度調查",
            "record_date": "2018-04-23",
            "original_station_or_locality": "石朗(Shihlang)",
            "original_latitude": 22.654828,
            "original_longitude": 121.473514,
            "distance_m": haversine(22.65791, 121.47449, 22.654828, 121.473514),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:measurementorfact.txt",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "excluded_unrelated_habitat",
            "justification": "港區內部無珊瑚礁底質覆蓋度紀錄；不可將 357.1m 外石朗珊瑚礁測線數據套用至人造碼頭與泊船區。"
        },
        {
            "candidate_id": "CAND-NL-EDNA-01",
            "site_id": "tourism-attraction-376540000a-000367",
            "site_name": "綠島南寮漁港",
            "evidence_type": "environmental_dna",
            "taxon_scientific_name": "Acanthurus lineatus",
            "taxon_chinese_name": "線紋刺尾鯛",
            "taxon_group": "魚類",
            "survey_method": "水樣抽濾與次世代定序 (12S eDNA metabarcoding)",
            "record_date": "2022-06-28",
            "original_station_or_locality": "TRM59",
            "original_latitude": 22.654467,
            "original_longitude": 121.472817,
            "distance_m": haversine(22.65791, 121.47449, 22.654467, 121.472817),
            "source_name": "海洋委員會海洋保育署 (OCA) 全海域基礎生態調查環境DNA",
            "source_dataset_id": "edna_diving_110_113.json:TRM59",
            "source_url": "https://data.gov.tw/dataset/172487",
            "license_name": "政府資料開放授權條款-第1版 (OGL 1.0)",
            "license_status": "open_government_license",
            "decision": "accepted_historical_dna_evidence",
            "justification": "取樣點 TRM59 位於漁港西南外海約 419.6m，反映周邊近岸水體之環境 DNA 分子訊號；不可宣稱為港池內肉眼可見物種。"
        },
        {
            "candidate_id": "CAND-NL-TAX-01",
            "site_id": "tourism-attraction-376540000a-000367",
            "site_name": "綠島南寮漁港",
            "evidence_type": "taxonomic_catalog",
            "taxon_scientific_name": "Sphyraena barracuda",
            "taxon_chinese_name": "巴拉金梭魚",
            "taxon_group": "魚類",
            "survey_method": "分類學名錄整編 (無空間座標/無調查日期)",
            "record_date": "",
            "original_station_or_locality": "全臺魚類分類名錄(無地名)",
            "original_latitude": None,
            "original_longitude": None,
            "distance_m": None,
            "source_name": "中央研究院生物多樣性研究中心 臺灣魚類資料庫",
            "source_dataset_id": "臺灣魚類資料庫.csv",
            "source_url": "https://fishdb.sinica.edu.tw/",
            "license_name": "TaiBIF / TaiCoL 授權條款待確認",
            "license_status": "pending_verification",
            "decision": "excluded_taxonomy_only",
            "justification": "分類名錄無點位與調查紀錄，排除作為潛點生態事實。"
        },

        # ==========================================
        # Site 3: 柴口浮潛區 (tourism-attraction-376540000a-000478)
        # ==========================================
        {
            "candidate_id": "CAND-CK-RC-01",
            "site_id": "tourism-attraction-376540000a-000478",
            "site_name": "柴口浮潛區",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Chaetodontidae",
            "taxon_chinese_name": "蝶魚科",
            "taxon_group": "魚類",
            "survey_method": "Reef Check 水下穿越線目視計數 (Belt Transect)",
            "record_date": "2018-04-23",
            "original_station_or_locality": "柴口(Chaikou)",
            "original_latitude": 22.677589,
            "original_longitude": 121.481543,
            "distance_m": haversine(22.67739, 121.48268, 22.677589, 121.481543),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:event_2018_TTLudao_Chaikou_deep_0-20",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "測線距潛點代表點 118.7m；具明確目視指標計數紀錄。僅限非商業研究模式，且不得宣稱為現況。"
        },
        {
            "candidate_id": "CAND-CK-RC-02",
            "site_id": "tourism-attraction-376540000a-000478",
            "site_name": "柴口浮潛區",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Lutjanidae",
            "taxon_chinese_name": "笛鯛科",
            "taxon_group": "魚類",
            "survey_method": "Reef Check 水下穿越線目視計數",
            "record_date": "2018-04-23",
            "original_station_or_locality": "柴口(Chaikou)",
            "original_latitude": 22.677589,
            "original_longitude": 121.481543,
            "distance_m": haversine(22.67739, 121.48268, 22.677589, 121.481543),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:event_2018_TTLudao_Chaikou_shallow_25-45",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "測線距潛點 118.7m。歷史目視調查紀錄，受 CC BY-NC 4.0 約束。"
        },
        {
            "candidate_id": "CAND-CK-RC-03",
            "site_id": "tourism-attraction-376540000a-000478",
            "site_name": "柴口浮潛區",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Tridacna sp.",
            "taxon_chinese_name": "砗磲貝屬",
            "taxon_group": "無脊椎動物",
            "survey_method": "Reef Check 水下穿越線無脊椎計數",
            "record_date": "2018-04-23",
            "original_station_or_locality": "柴口(Chaikou)",
            "original_latitude": 22.677589,
            "original_longitude": 121.481543,
            "distance_m": haversine(22.67739, 121.48268, 22.677589, 121.481543),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:event_2018_TTLudao_Chaikou_deep_25-45",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "距潛點 118.7m 之無脊椎穿越線紀錄；非商業研究模式，不保證現地可見。"
        },
        {
            "candidate_id": "CAND-CK-RC-04",
            "site_id": "tourism-attraction-376540000a-000478",
            "site_name": "柴口浮潛區",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Scleractinia (hard coral)",
            "taxon_chinese_name": "硬珊瑚/石珊瑚覆蓋度",
            "taxon_group": "珊瑚",
            "survey_method": "Reef Check 點截線底質覆蓋度調查 (Point Intercept Transect)",
            "record_date": "2008-07-28",
            "original_station_or_locality": "柴口(Chaikou)",
            "original_latitude": 22.677589,
            "original_longitude": 121.481543,
            "distance_m": haversine(22.67739, 121.48268, 22.677589, 121.481543),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:measurementorfact.txt",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "距潛點 118.7m 測線之硬珊瑚覆蓋度 (30.0%–52.5%)；歷史群落底質數據，不得表述為目前現況。"
        },
        {
            "candidate_id": "CAND-CK-EDNA-01",
            "site_id": "tourism-attraction-376540000a-000478",
            "site_name": "柴口浮潛區",
            "evidence_type": "environmental_dna",
            "taxon_scientific_name": "Abudefduf septemfasciatus",
            "taxon_chinese_name": "七帶豆娘魚",
            "taxon_group": "魚類",
            "survey_method": "水樣抽濾與次世代定序 (12S eDNA metabarcoding)",
            "record_date": "2024-06-07",
            "original_station_or_locality": "ChaiK",
            "original_latitude": 22.6775,
            "original_longitude": 121.48222,
            "distance_m": haversine(22.67739, 121.48268, 22.6775, 121.48222),
            "source_name": "海洋委員會海洋保育署 (OCA) 全海域基礎生態調查環境DNA",
            "source_dataset_id": "edna_diving_110_113.json:ChaiK",
            "source_url": "https://data.gov.tw/dataset/172487",
            "license_name": "政府資料開放授權條款-第1版 (OGL 1.0)",
            "license_status": "open_government_license",
            "decision": "accepted_historical_dna_evidence",
            "justification": "採樣點距潛點僅 48.8m；為近期水樣 DNA 訊號。不可冒稱為肉眼必然可見。"
        },
        {
            "candidate_id": "CAND-CK-EDNA-02",
            "site_id": "tourism-attraction-376540000a-000478",
            "site_name": "柴口浮潛區",
            "evidence_type": "environmental_dna",
            "taxon_scientific_name": "Acanthurus nigrofuscus",
            "taxon_chinese_name": "褐斑刺尾鯛",
            "taxon_group": "魚類",
            "survey_method": "水樣抽濾與次世代定序 (12S eDNA metabarcoding)",
            "record_date": "2022-06-27",
            "original_station_or_locality": "TRM53",
            "original_latitude": 22.678983,
            "original_longitude": 121.47965,
            "distance_m": haversine(22.67739, 121.48268, 22.678983, 121.47965),
            "source_name": "海洋委員會海洋保育署 (OCA) 全海域基礎生態調查環境DNA",
            "source_dataset_id": "edna_diving_110_113.json:TRM53",
            "source_url": "https://data.gov.tw/dataset/172487",
            "license_name": "政府資料開放授權條款-第1版 (OGL 1.0)",
            "license_status": "open_government_license",
            "decision": "accepted_historical_dna_evidence",
            "justification": "採樣點距潛點 357.8m；水體環境 DNA 檢出分子訊號。"
        },
        {
            "candidate_id": "CAND-CK-IMG-01",
            "site_id": "tourism-attraction-376540000a-000478",
            "site_name": "柴口浮潛區",
            "evidence_type": "monitoring_site_media",
            "taxon_scientific_name": "Scleractinia spp.",
            "taxon_chinese_name": "珊瑚礁群落 (監測站影像)",
            "taxon_group": "珊瑚",
            "survey_method": "定點水下生態攝影 (海域生態監測站)",
            "record_date": "",
            "original_station_or_locality": "綠島北岸(珊瑚礁)",
            "original_latitude": 22.6772,
            "original_longitude": 121.4925,
            "distance_m": haversine(22.67739, 121.48268, 22.6772, 121.4925),
            "source_name": "國家海洋研究院 (NAMR) 海域生態監測站點圖資",
            "source_dataset_id": "海域生態監測站點/36_綠島北岸(珊瑚礁).jpg",
            "source_url": "https://nodass.namr.gov.tw/noapidata/Tile/eDNA/mecrcPoint/36_綠島北岸(珊瑚礁).jpg",
            "license_name": "著作權未確認 (版權保留)",
            "license_status": "copyright_unclear_or_reserved",
            "decision": "pending_rights_review",
            "justification": "距潛點 1.01 km；雖位於綠島北岸同一海域，但照片著作權未明，嚴禁下載、複製或內嵌展示。"
        },

        # ==========================================
        # Site 4: 大白沙 (tourism-attraction-a15010100h-000067)
        # ==========================================
        {
            "candidate_id": "CAND-DBS-RC-01",
            "site_id": "tourism-attraction-a15010100h-000067",
            "site_name": "大白沙",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Chaetodontidae",
            "taxon_chinese_name": "蝶魚科",
            "taxon_group": "魚類",
            "survey_method": "Reef Check 水下穿越線目視計數 (Belt Transect)",
            "record_date": "2018-04-23",
            "original_station_or_locality": "大白沙(Dabaisha)",
            "original_latitude": 22.639209,
            "original_longitude": 121.491964,
            "distance_m": haversine(22.63722, 121.49385, 22.639209, 121.491964),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:event_2018_TTLudao_Dabaisha_deep_0-20",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "測線距潛點 293.9m；具明確目視指標紀錄。限非商業研究模式，不得表述為現況。"
        },
        {
            "candidate_id": "CAND-DBS-RC-02",
            "site_id": "tourism-attraction-a15010100h-000067",
            "site_name": "大白沙",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Acanthaster plancii",
            "taxon_chinese_name": "棘冠海星/魔鬼海星",
            "taxon_group": "無脊椎動物",
            "survey_method": "Reef Check 水下穿越線無脊椎計數",
            "record_date": "2016-08-20",
            "original_station_or_locality": "大白沙(Dabaisha)",
            "original_latitude": 22.637538,
            "original_longitude": 121.491055,
            "distance_m": haversine(22.63722, 121.49385, 22.637538, 121.491055),
            "distance_m": 289.0,
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:event_2016_TTLudao_Dabaisha_shallow_25-45",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "測線距潛點 289.0m；記錄到珊瑚天敵棘冠海星。非商業研究模式，屬歷史調查，不得表述為目前生態威脅現況。"
        },
        {
            "candidate_id": "CAND-DBS-RC-03",
            "site_id": "tourism-attraction-a15010100h-000067",
            "site_name": "大白沙",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Scleractinia (hard coral)",
            "taxon_chinese_name": "硬珊瑚/石珊瑚覆蓋度",
            "taxon_group": "珊瑚",
            "survey_method": "Reef Check 點截線底質覆蓋度調查 (Point Intercept Transect)",
            "record_date": "2018-04-23",
            "original_station_or_locality": "大白沙(Dabaisha)",
            "original_latitude": 22.639209,
            "original_longitude": 121.491964,
            "distance_m": haversine(22.63722, 121.49385, 22.639209, 121.491964),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:measurementorfact.txt",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "accepted_historical_visual_evidence",
            "justification": "距潛點 293.9m 測線之硬珊瑚覆蓋度紀錄；屬歷史底質生態指標，不得表述為現況。"
        },
        {
            "candidate_id": "CAND-DBS-EDNA-01",
            "site_id": "tourism-attraction-a15010100h-000067",
            "site_name": "大白沙",
            "evidence_type": "environmental_dna",
            "taxon_scientific_name": "Calotomus carolinus",
            "taxon_chinese_name": "卡羅鸚鯉",
            "taxon_group": "魚類",
            "survey_method": "水樣抽濾與次世代定序 (12S eDNA metabarcoding)",
            "record_date": "2023-07-10",
            "original_station_or_locality": "DRM2",
            "original_latitude": 22.63748,
            "original_longitude": 121.4887,
            "distance_m": haversine(22.63722, 121.49385, 22.63748, 121.4887),
            "source_name": "海洋委員會海洋保育署 (OCA) 全海域基礎生態調查環境DNA",
            "source_dataset_id": "edna_diving_110_113.json:DRM2",
            "source_url": "https://data.gov.tw/dataset/172487",
            "license_name": "政府資料開放授權條款-第1版 (OGL 1.0)",
            "license_status": "open_government_license",
            "decision": "accepted_historical_dna_evidence",
            "justification": "採樣站距潛點 529.3m；為水體環境 DNA 檢出分子訊號。嚴禁表述為肉眼可見。"
        },
        {
            "candidate_id": "CAND-DBS-EDNA-02",
            "site_id": "tourism-attraction-a15010100h-000067",
            "site_name": "大白沙",
            "evidence_type": "environmental_dna",
            "taxon_scientific_name": "Azurina lepidolepis",
            "taxon_chinese_name": "細鱗光鰓雀鯛",
            "taxon_group": "魚類",
            "survey_method": "水樣抽濾與次世代定序 (12S eDNA metabarcoding)",
            "record_date": "2022-06-30",
            "original_station_or_locality": "TRM61",
            "original_latitude": 22.639983,
            "original_longitude": 121.489167,
            "distance_m": haversine(22.63722, 121.49385, 22.639983, 121.489167),
            "source_name": "海洋委員會海洋保育署 (OCA) 全海域基礎生態調查環境DNA",
            "source_dataset_id": "edna_diving_110_113.json:TRM61",
            "source_url": "https://data.gov.tw/dataset/172487",
            "license_name": "政府資料開放授權條款-第1版 (OGL 1.0)",
            "license_status": "open_government_license",
            "decision": "accepted_historical_dna_evidence",
            "justification": "距潛點 570.4m 採樣站之水樣 DNA 訊號。不可保證現場必然目擊。"
        },
        {
            "candidate_id": "CAND-DBS-TAX-01",
            "site_id": "tourism-attraction-a15010100h-000067",
            "site_name": "大白沙",
            "evidence_type": "taxonomic_catalog",
            "taxon_scientific_name": "Platax teira",
            "taxon_chinese_name": "圓眼燕魚",
            "taxon_group": "魚類",
            "survey_method": "分類學名錄整編 (無空間座標/無調查日期)",
            "record_date": "",
            "original_station_or_locality": "全臺魚類分類名錄(無地名)",
            "original_latitude": None,
            "original_longitude": None,
            "distance_m": None,
            "source_name": "中央研究院生物多樣性研究中心 臺灣魚類資料庫",
            "source_dataset_id": "臺灣魚類資料庫.csv",
            "source_url": "https://fishdb.sinica.edu.tw/",
            "license_name": "TaiBIF / TaiCoL 授權條款待確認",
            "license_status": "pending_verification",
            "decision": "excluded_taxonomy_only",
            "justification": "分類名錄無點位與調查紀錄，排除作為潛點生態事實。"
        },

        # ==========================================
        # Site 5: 險礁嶼 (tourism-attraction-a15010200h-000004 - 澎湖白沙)
        # ==========================================
        {
            "candidate_id": "CAND-XJ-RC-01",
            "site_id": "tourism-attraction-a15010200h-000004",
            "site_name": "險礁嶼",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "Chaetodontidae",
            "taxon_chinese_name": "蝶魚科",
            "taxon_group": "魚類",
            "survey_method": "Reef Check 水下穿越線目視計數 (Belt Transect)",
            "record_date": "2018-06-09",
            "original_station_or_locality": "鐵砧東(TiezhenEast)",
            "original_latitude": 23.275733,
            "original_longitude": 119.504939,
            "distance_m": haversine(23.7118, 119.608, 23.275733, 119.504939),
            "source_name": "台灣珊瑚礁學會 / TaiBIF 台灣珊瑚礁體檢 (Reef Check Taiwan)",
            "source_dataset_id": "reefcheck_taiwan_dwca:event_2018_PEHWangAn_DongyupingEast_NA_25-45",
            "source_url": "https://ipt.taibif.tw/resource?r=reefcheck_taiwan",
            "license_name": "CC BY-NC 4.0",
            "license_status": "cc_by_nc_4_0",
            "decision": "excluded_too_distant",
            "justification": "最近之珊瑚礁體檢測線位於澎湖南方四島鐵砧東，距險礁嶼高達 49.6 公里 (49,614m)！兩地水文與珊瑚礁群落截然不同，絕對嚴禁冒充為險礁嶼潛點生態紀錄。"
        },
        {
            "candidate_id": "CAND-XJ-EDNA-01",
            "site_id": "tourism-attraction-a15010200h-000004",
            "site_name": "險礁嶼",
            "evidence_type": "environmental_dna",
            "taxon_scientific_name": "Ablennes hians",
            "taxon_chinese_name": "扁鶴鱵",
            "taxon_group": "魚類",
            "survey_method": "水樣抽濾與次世代定序 (12S eDNA metabarcoding)",
            "record_date": "2021-05-10",
            "original_station_or_locality": "TRM33",
            "original_latitude": 23.71258,
            "original_longitude": 119.56742,
            "distance_m": haversine(23.7118, 119.608, 23.71258, 119.56742),
            "source_name": "海洋委員會海洋保育署 (OCA) 全海域基礎生態調查環境DNA",
            "source_dataset_id": "edna_diving_110_113.json:TRM33",
            "source_url": "https://data.gov.tw/dataset/172487",
            "license_name": "政府資料開放授權條款-第1版 (OGL 1.0)",
            "license_status": "open_government_license",
            "decision": "excluded_too_distant",
            "justification": "最近測站 TRM33 位於吉貝外海航道，距離險礁嶼潛點達 4.13 公里 (4,132m)，超出近岸礁區水體代表半徑，無法代表險礁嶼現地生態，排除採用。"
        },
        {
            "candidate_id": "CAND-XJ-NMMBA-01",
            "site_id": "tourism-attraction-a15010200h-000004",
            "site_name": "險礁嶼",
            "evidence_type": "historical_visual_survey",
            "taxon_scientific_name": "待確認（Excel 未解析群落）",
            "taxon_chinese_name": "海生中心示範海域群落",
            "taxon_group": "綜合",
            "survey_method": "海生中心示範海域生態調查",
            "record_date": "2021-11-24",
            "original_station_or_locality": "澎湖海域示範區（具體站點待確認）",
            "original_latitude": None,
            "original_longitude": None,
            "distance_m": None,
            "source_name": "國立海洋生物博物館 (NMMBA) 全國海洋資料庫展示資料",
            "source_dataset_id": "110.11.24_海生中心示範海域生態資料_全國海洋資料庫展示用(澎湖海域).xlsx",
            "source_url": "本機存檔（授權與站點清單待向 NMMBA 確認）",
            "license_name": "授權待確認",
            "license_status": "pending_verification",
            "decision": "pending_missing_fields",
            "justification": "Excel 檔案未解析經緯度與站點，且開放授權尚未向 NMMBA 確認；目前無證據支持其包含險礁嶼周邊調查，列為待審。"
        },
        {
            "candidate_id": "CAND-XJ-IMG-01",
            "site_id": "tourism-attraction-a15010200h-000004",
            "site_name": "險礁嶼",
            "evidence_type": "monitoring_site_media",
            "taxon_scientific_name": "Zostera / Halophila spp.",
            "taxon_chinese_name": "海草床生態群落 (監測站影像)",
            "taxon_group": "植物/海草",
            "survey_method": "定點水下生態攝影 (海域生態監測站)",
            "record_date": "",
            "original_station_or_locality": "澎湖本島周遭海域(海草床)",
            "original_latitude": 23.6479,
            "original_longitude": 119.6048,
            "distance_m": haversine(23.7118, 119.608, 23.6479, 119.6048),
            "source_name": "國家海洋研究院 (NAMR) 海域生態監測站點圖資",
            "source_dataset_id": "海域生態監測站點/40_澎湖本島周遭海域(海草床).jpg",
            "source_url": "https://nodass.namr.gov.tw/noapidata/Tile/eDNA/mecrcPoint/40_澎湖本島周遭海域(海草床).jpg",
            "license_name": "著作權未確認 (版權保留)",
            "license_status": "copyright_unclear_or_reserved",
            "decision": "pending_rights_review",
            "justification": "距離險礁嶼 7.11 km（位於澎湖岐頭海草床）；影像著作權未確認開放，嚴禁下載、複製或內嵌。"
        },
        {
            "candidate_id": "CAND-XJ-TAX-01",
            "site_id": "tourism-attraction-a15010200h-000004",
            "site_name": "險礁嶼",
            "evidence_type": "taxonomic_catalog",
            "taxon_scientific_name": "Lethrinus nebulosus",
            "taxon_chinese_name": "青嘴龍占",
            "taxon_group": "魚類",
            "survey_method": "分類學名錄整編 (無空間座標/無調查日期)",
            "record_date": "",
            "original_station_or_locality": "全臺魚類分類名錄(無地名)",
            "original_latitude": None,
            "original_longitude": None,
            "distance_m": None,
            "source_name": "中央研究院生物多樣性研究中心 臺灣魚類資料庫",
            "source_dataset_id": "臺灣魚類資料庫.csv",
            "source_url": "https://fishdb.sinica.edu.tw/",
            "license_name": "TaiBIF / TaiCoL 授權條款待確認",
            "license_status": "pending_verification",
            "decision": "excluded_taxonomy_only",
            "justification": "名錄無座標無日期，無法證明險礁嶼出現紀錄。"
        }
    ]

    fieldnames = [
        "candidate_id",
        "site_id",
        "site_name",
        "evidence_type",
        "taxon_scientific_name",
        "taxon_chinese_name",
        "taxon_group",
        "survey_method",
        "record_date",
        "original_station_or_locality",
        "original_latitude",
        "original_longitude",
        "distance_m",
        "source_name",
        "source_dataset_id",
        "source_url",
        "license_name",
        "license_status",
        "decision",
        "justification"
    ]

    with open(OUTPUT_CSV, "w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in candidates:
            # clean None to empty string
            clean_row = {k: ("" if v is None else v) for k, v in row.items()}
            writer.writerow(clean_row)
    print(f"Wrote {len(candidates)} candidate rows to {OUTPUT_CSV}")

if __name__ == "__main__":
    main()
